### ISSUE TITLE
compatibility with modded items

### ISSUE THREAD

**Issue by peow** [Emafire003/BeamPass#1]
it seems that BeamPass does not fully support blocks from other mods, I tested for example the following items:

"glasscarpet:tinted_glass_carpet" from https://modrinth.com/mod/glass-carpet *(the normal glass blocks from this mod work as expected)*

"natures_spirit:red_moss_block" from https://modrinth.com/mod/natures-spirit

"twigs:lamp" from https://modrinth.com/mod/twigs

![2024-03-25_19 24 09](https://github.com/Emafire003/BeamPass/assets/105888751/f0010e59-e304-49d2-aa02-2eb1b09e97ca)

my config file - 
[beampass_blocklist.json](https://github.com/Emafire003/BeamPass/files/14750182/beampass_blocklist.json)

*im using BeamPass v1.3.1 to Fabric 1.20.1*

**Comment by peow** [comment]
thanks
the new update will not be backported to 1.20.1?

**Comment by Emafire003** [comment]
Uploading the 1.20.1 backport now.
